### ISSUE TITLE
请问这个怎么运行

### ISSUE THREAD

**Issue by cwm881012** [alpha87/SJXF-SCF#1]
如回复将不胜感激额

**Comment by alpha87** [comment]
有两种运行方式：

1. 安装好依赖（requests，loguru）直接运行
2. 部署到腾讯云上使用云函数每日定时运行

主要文件是 index.py，其他文件夹是部署到腾讯云所需要的第三方依赖。

推荐在腾讯云注册账号，部署到腾讯云上每日定时执行。

**Comment by cwm881012** [comment]
这个对我这样的小白难度确实不小，折腾了一会，还是搞不定啊，不会安装依赖环境

**Comment by alpha87** [comment]
如果是腾讯云函数，直接上传此文件夹就可以执行；如果本地运行，使用 pip install requests loguru 安装依赖。

**Comment by cwm881012** [comment]
你好，这个已经部署成功，请问用户名和密码需要怎么修改，加密的密码获取方式？太小白了我

**Comment by alpha87** [comment]
尝试运行这部分代码：[https://raw.githubusercontent.com/RuikaiWang/Study/master/PassWordEncode.py](https://raw.githubusercontent.com/RuikaiWang/Study/master/PassWordEncode.py)

**Comment by cwm881012** [comment]
您好，我已经安装aes运行，获取加密后的密码，修改了您index.py中的tel1和pd1，部署到腾讯云函数测试成功，返回的结果是null,请问这个是哪里需要再修改吗？

**Comment by alpha87** [comment]
云函数正常运行会返回 null，你看一下三晋先锋有无积分，如果有积分说明已经开始正常运行了。

**Comment by cwm881012** [comment]
测试了2次，没有增加积分，呵呵

**Comment by cwm881012** [comment]
不知道是不是还有哪里不正确，所以请教一下大佬

**Comment by alpha87** [comment]
拉取新的代码尝试一下。python 运行打印的日志有提示什么错误吗？

**Comment by cwm881012** [comment]
部署后测试成功的，我就修改了index.py的两个地方，一个是把tel1修改成自己的手机号，一个是pd1修改成aes加密后的密码。执行后的日志为

START RequestId: 77181167-abf6-4ed5-82a3-e4c5cbab757a

Event RequestId: 77181167-abf6-4ed5-82a3-e4c5cbab757a

Starting new HTTP connection (1): 221.204.170.88:8184

http://221.204.170.88:8184 "POST /app/user/login HTTP/1.1" 200 274

Exception in thread Thread-1:

Traceback (most recent call last):

  File "/var/lang/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner

    self.run()

  File "/var/lang/python3/lib/python3.6/threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "/var/user/index.py", line 430, in main

    password=user["password"])

  File "/var/user/index.py", line 132, in login

    info = json.loads(base64.b64decode(user_auth_info))

  File "/var/lang/python3/lib/python3.6/json/__init__.py", line 354, in loads

    return _default_decoder.decode(s)

  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 339, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)



END RequestId: 77181167-abf6-4ed5-82a3-e4c5cbab757a

Report RequestId: 77181167-abf6-4ed5-82a3-e4c5cbab757a Duration:42ms Memory:128MB MemUsage:17.2383MB

**Comment by alpha87** [comment]
最新版输入用户名和密码，直接可以在本地运行。

**Comment by cwm881012** [comment]
谢谢您的回复，希望越做越好发自我的华为手机-------- 原始邮件 --------发件人： 简讯 <notifications@github.com>日期： 2021年2月22日周一 20:48收件人： alpha87/SJXF-SCF <SJXF-SCF@noreply.github.com>抄送： cwm881012 <android@yeah.net>, Author <author@noreply.github.com>主    题： Re: [alpha87/SJXF-SCF] 请问这个怎么运行 (#1)

最新版输入用户名和密码，直接可以在本地运行。

**Comment by cwm881012** [comment]
你好，我修改了账号密码，手机号和密码都填入了啊，但是云函数运行出错，请问问题可能出在哪
             “clientid": "234234",
            "deviceId": "imei867391035223309",
            "password": 1XXXXX3,
            "userName": 139XXXXX,
            "verifyCode": ""

**Comment by alpha87** [comment]
**修改代码 32 行即可，其他地方无需修改**：

```python
user_list = [
    {
        "username": 139XXXXX,
        "password": 1XXXXX3
    }
]
```

如果运行成功帮忙点个 star，谢谢🙏

**Comment by cwm881012** [comment]
亲，已经修改第32行的user_list = [
    {
        "username": 139XXXXX,
        "password": 1XXXXX3
    }
]
，现在在本地运行出现的是错误提示    File "C:\Users\Smith\Desktop\SJXF-SCF-main\index.py", line 35, in <module>
    "password": ZXXXX
NameError: name 'ZXXXX' is not defined  ，感谢您的指导！

**Comment by alpha87** [comment]
> 亲，已经修改第32行的user_list = [
> {
> "username": 139XXXXX,
> "password": 1XXXXX3
> }
> ]
> ，现在在本地运行出现的是错误提示 File "C:\Users\Smith\Desktop\SJXF-SCF-main\index.py", line 35, in
> "password": ZXXXX
> NameError: name 'ZXXXX' is not defined ，感谢您的指导！

写了一个桌面版，看看你是否可以正常运行：[https://github.com/alpha87/SJXF-SCF/releases](https://github.com/alpha87/SJXF-SCF/releases)
